 &SCENARIO
  BSP = 'MCMgas'
  pHSet = 1
  MinScav = 0.05d0
  MinChem = 0.05d0
  LWCLevel = 1.d-15 
  MaxFrac  = 1
  mAcoeff = 0
  mPitz   = 0
  mUni    = 0
  mJacIO  = 1
  nDep    = 1
  nDepAqua  = 1
  Ladebalken = 1
 /END
 &FILES
  ChemFile = 'CHEM/RACM'
  DataFile = 'CHEM/RACM.dat'
  JacFile  = 'INPUT/MCM32_gas.jac'
  InitFile = 'INI/urban.ini'
  MetFile  = 'MET/1day_wocloud.met'
 /END
 &TIMES
  DtCoupl = 100.d0
  tAnf=0.0d0
  tEnd=86400.0d0
  StpAVS  = 100.d0
  StpOut  = 600.d0
  StpDiag = 600.d0
  dStart  = 0.d0
  Ipoint1 = 999
  tSimul  = 0.d0
  Dust    = 0.5d0
  idate   = 010619     
  rlat    = 45.d0     
  rlon    =  0.d0
  maxStp  = 1000.d0
/END
 &METEO
  mpMod   = 2
  mCase   = 1
  ItemEnd = 10
  VdepDrop = 0.0
  nfRaoult = 0
  nfMass   = 0
 /END
 &NUMERICS
  LinSolv = 3
  RtolROW  = 1.0d-3
  AtolGas  = 1.0d-1
  AtolAqua = 1.0d-7
  solveLA = 'ex'  
  RosenbrockMethod = 'METHODS/Ros34PW2.fort'
 /END
 &ORDERING
  OrderingStrategie      = 1
  FactorisationStrategie = 1
  SolLinSystemStrategie    = 1
 /END
 &ENTRAIN
 /END
