 &SCENARIO
  BSP = 'SmallStratoKPPcl'
  pHSet = 1
  LWCLevelmax = 2.d-8
  LWCLevelmin = 3.d-6 
  constLWC = 0
  Ladebalken = 0
  ErrorLog = 0
  matrixPrint = .false.  
  NetCdfPrint = .false.
 /END
 &FILES
  ChemFile = 'CHEM/SmallStratoKPP'
  DataFile = 'DAT/RACM.dat'
  InitFile = 'INI/SmallStratoKPP.ini'
  MetFile  = 'MET/1day_wocloud.met'
 /END
 &TIMES
  tAnf=0.0d0
  tEnd=86400.0d0
  Dust    = 0.5d0
  idate   = 010619     
  rlat    = 45.d0     
  rlon    =  0.d0
  minStp  = 1.0d-25
  maxStp  = 100.d0
/END
 &NUMERICS
  LinSolv = 3
  RtolROW  = 1.0d-2
  AtolGas  = 1.0d-4
  AtolAqua  = 1.0d-4
  Error_Est = 2
  solveLA = 'cl'  
  !RosenbrockMethod = 'METHODS/Ros2AMF.fort'    
  !RosenbrockMethod = 'METHODS/Ros3w.fort'
  !RosenbrockMethod = 'METHODS/Ros3Pw.fort'
  !RosenbrockMethod = 'METHODS/Ros3Dw.fort'
  !RosenbrockMethod = 'METHODS/Ros34PW1a.fort'
  !RosenbrockMethod = 'METHODS/Ros34PW2.fort'
  !RosenbrockMethod = 'METHODS/Ros34PW3.fort'
  !RosenbrockMethod = 'METHODS/TSRosW2P.fort'  
  !RosenbrockMethod = 'METHODS/TSRosW2M.fort'   
  !RosenbrockMethod = 'METHODS/TSRosWRA3PW.fort'
  !RosenbrockMethod = 'METHODS/TSRosWRA34PW2.fort'  
  RosenbrockMethod = 'METHODS/TSRosWRodas3.fort'
  !RosenbrockMethod = 'METHODS/TSRosWSandu3.fort'
  ImpEuler = 0
 /END
 &ORDERING
  OrderingStrategie      = 8
  ParOrdering = -1
 /END
 &ENTRAIN
 /END
