 &SCENARIO
  BSP = 'Urban_Orig'
  pHSet = 1
  LWCLevelmin = 2.0d-14
  LwcLevelmax = 3.0d-10
  Ladebalken = 1 
  ErrorLog = 0
 /END
 &FILES
  ChemFile = 'CHEM/Urban_ORIG'
  DataFile = 'DAT/Urban_ORIG.dat'
  InitFile = 'INI/Urban.ini'
  MetFile  = 'MET/Urban.met'
 /END
 &TIMES
  tAnf=0.0d0
  tEnd=84600.0d0
  Dust    = 0.5d0
  idate   = 010619     
  rlat    = 45.d0     
  rlon    =  0.d0
  minStp  = 1.0d-30
  maxStp  = 300.d0
/END
 &METEO
 /END
 &NUMERICS
  LinSolv = 3
  RtolROW  = 1.0d-2
  AtolGas  = 1.0d-3
  AtolAqua = 1.0d-3
  solveLA = 'ex'  
  RosenbrockMethod = 'METHODS/Ros34PW2.fort'
  ImpEuler = 0
 /END
 &ORDERING
  OrderingStrategie      = 8
  FactorisationStrategie = 1
  SolLinSystemStrategie  = 1
 /END
 &ENTRAIN
 /END
