 &SCENARIO
  BSP = 'Wasserstoff'               ! Name der NetCDF Output-Datei
  pHSet = 1                        ! berechne pH Wert zu Beginn
  LWCLevelmin = 2.0d-14            ! minimaler LWC Wert
  LWCLevelmax = 3.0d-10            ! maximaler LWC Wert
  constLWC = 1                     ! 0 = konstanter LWC wert, 0 /= pseudo LWC funktion wird benutzt
  Ladebalken = 1                   ! 0 = kein ladebalken, 0 /= ladebalken aktiv
  ErrorLog = 0                     ! 0 = no error output, 0 /= error output direkt auf bildschirm
  MatrixPrint = .false.             ! .TRUE. == print matricies (no simulation),  .FALSE. == do not print any matrix
 /END
 &FILES
  ChemFile = 'ckCHEM/Wasserstoff/Wasserstoff'             ! .sys Datei (ohne .sys angeben!)
  DataFile = 'ckCHEM/Wasserstoff/Wasserstoff.dat'         ! .dat Datei thermodynamische Daten
  InitFile = 'INI/Wasserstoff.ini'          ! .ini Datei (Anfangswerte gas/flüssig), Diagnose spc
  MetFile  = 'MET/1day_wocloud.met'   ! .met Datei (Meteorologie Datei)
 /END
 &TIMES
  tAnf=0.0d0                          ! Startzeit Integration
  tEnd=84400.0d0                      ! Endzeit   Integration
  Dust    = 0.5d0                     ! Zenith Berechnung       (Staub)
  idate   = 010619                    ! ---------''---------    (Datum: DDMMYY)
  rlat    = 45.d0                     ! ---------''---------    (Breitengrad)
  rlon    =  0.d0                     ! ---------''---------    (Längengrad)
  minStp  = 1.0d-30                   ! minimale Schrittweite für Integration
  maxStp  = 200.d0                    ! maximale Schrittweite für Integration
/END
 &NUMERICS
  RtolROW  = 1.0d-2                             ! rel. Toleranz für Rosenbrock-Wanner Fehlersteuerung
  AtolGas  = 1.0d-3                             ! abs. Toleranzen für gasförmige Stoffe 
  AtolAqua = 1.0d-3                             ! abs. Toleranzen für aquatische Stoffe
  solveLA = 'ex'                                ! 'ex'=extended Blockmatrix, 'cl'=klassische Jacobimatrix
  RosenbrockMethod = 'METHODS/Ros34PW2.fort' !'METHODS/Ros34PW3.fort'    ! Rosenbrock-Wanner Verfahrenskoeffizienten
  ImpEuler = 0                                  ! 0=kein impliziter Euler, 1=impliziter Euler (kein ROW!!)
 /END
 &ORDERING
  OrderingStrategie      = 8                   ! 8=Markowitz(SparseLU) , 1,..,7=Mumps Orderings  
 /END
 &ENTRAIN
 /END
